import Header from '@/components/header';
import { Typography } from '@mui/material';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Foodie</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<Typography>
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque, soluta consequatur! Temporibus dicta expedita ipsa vero alias voluptate reiciendis obcaecati eum libero nulla vel
					placeat quae praesentium maiores, voluptates consequatur.
				</Typography>
			</main>
		</>
	);
}
